site_name: T-Order Docs
site_url: https://torder.newchurchill.eu
nav:
  - Home:
      - index.md
  - Introduzione:
      - introduzione/index.md
  - Ordini:
      - ordini/index.md
      - Tabelle Coinvolte: ordini/tabelle_coinvolte.md
      - Informazioni Ordine: ordini/informazioni_ordine.md
      - Ciclo Ordine: ordini/ciclo_ordine.md
  - Rinnovi:
      - rinnovi/index.md
      - Annuali/Biennali/31-12:
          - rinnovi/annuali/index.md
          - Generazione Rinnovo: rinnovi/annuali/generazione.md
          - Configurazione: rinnovi/annuali/configurazione.md
          - Disdetta: rinnovi/annuali/disdetta.md
          - Inserimento nuovi articoli: rinnovi/annuali/inserimento.md
          - Cambio Piano: rinnovi/annuali/cambio.md
          - Rinnovo: rinnovi/annuali/rinnovo.md
      - Mensili/Trimestrali/Semestrali: rinnovi/mensili-trimestrali-semestrali.md
  - Integrazioni: integrazioni.md
  - Analisi:
      - analisi/index.md
      - Database:
          - analisi/database/index.md
          - Schema: analisi/database/schema.md
          - Diagramma ER: analisi/database/er.md
      - Backend:
          - analisi/backend/index.md
          - Struttura: analisi/backend/struttura.md
          - Funzionalità:
              - analisi/backend/funzionalita/index.md
              - CRUD:
                  - analisi/backend/funzionalita/crud/index.md
                  - Query: analisi/backend/funzionalita/crud/query.md
              - Logiche di Business: analisi/backend/funzionalita/logiche-business.md
              - Servizi Aggiuntivi:
                  - analisi/backend/funzionalita/servizi/index.md
                  - Mail: analisi/backend/funzionalita/servizi/mail.md
                  - PDF: analisi/backend/funzionalita/servizi/pdf.md
                  - File Manager: analisi/backend/funzionalita/servizi/file.md
                  - Ospiti: analisi/backend/funzionalita/servizi/ospiti.md
      - Frontend: analisi/frontend.md
      - Javascript SDK: analisi/sdk.md
      - Autenticazione: autenticazione/index.md
  - Autenticazione:
      - autenticazione/index.md
      - Configurazione Auth0: autenticazione/auth0-config.md
      - Utenti:
          - autenticazione/utenti/index.md
          - Generazione Utente: autenticazione/utenti/generazione-utente.md
          - Privilegi e Ruoli: autenticazione/utenti/privilegi-ruoli.md
  - Esempi: esempi.md
  - Demo: demo.md
theme:
  name: material
  features:
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes
    - navigation.expand
    # - search.share # copy to clipboard button on search
  palette:
    - scheme: default
      toggle:
        icon: material/white-balance-sunny
        name: Attiva dark mode
    - scheme: slate
      toggle:
        icon: material/moon-waning-crescent
        name: Disattiva dark mode
  logo: assets/t-order-white.png
markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - def_list
extra_css:
  - stylesheets/extra.css
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/AndreFra96
copyright: Copyright &copy; 2019 - 2022 Andrea Brioschi
plugins:
  - search
  - swagger-ui-tag
  # - encryptcontent:
  #     global_password: "docuword"
  #     remember_password: True
  #     default_expire_dalay: 24
repo_url: https://github.com/AndreFra96/torder-docs
edit_uri: https://github.com/AndreFra96/torder-docs/tree/main/docs
# theme: readthedocs
